In [2]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.dtype)
arrr=np.array([1,2,3,4,'pree'])
print(arrr.dtype)

[1 2 3 4 5]
(5,)
int64
<U21


In [5]:
sq_arr=arr**2
print(sq_arr)

[ 1  4  9 16 25]


In [7]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)

(3, 3)
2
9


creating arrays from strach using inbuilt func

In [15]:
ar=np.zeros((3,4))
print(ar)
z=np.zeros((2,3),dtype='i')
print(z)
b=np.ones((4,),dtype='i')
print(b)
c=np.full((3,4),10)
print(c)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[1 1 1 1]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


Reshaping Arrays

In [21]:
arr=np.array([[1,2,3],[4,5,6]])
print("array before reshape with 3,2 : \n",arr)
arr_r=arr.reshape((2,3))
print("array after reshape with 2,3 : \n",arr_r)
arrr=arr.flatten()
print("flattended array: ",arrr)

array before reshape with 3,2 : 
 [[1 2 3]
 [4 5 6]]
array after reshape with 2,3 : 
 [[1 2 3]
 [4 5 6]]
flattended array:  [1 2 3 4 5 6]


Indexing - Fancy and boolean

In [23]:
arr=np.array([1,2,3,4,5])
idx=[0,2,4]
print(arr[idx])
print(arr[arr>4])

[1 3 5]
[5]


Slicing

In [27]:
arr=np.arange(1,11)
print(arr[4:9])

[5 6 7 8 9]


In [29]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:3])

[6 7]
